play_motion:
  controllers: [arm_controller, head_controller, torso_controller, gripper_controller]
  motions:
    home:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.18, 0.21, 0.35, 0.1, 0.0, -1.57, 0.0, 0.0]
        time_from_start: 0.0
      - positions: [0.18, 0.21, 0.35, -0.20, 0.0, -1.57, 1.37, 0.0]
        time_from_start: 1.5
      - positions: [0.18, 0.20, 0.35, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 3.5
      - positions: [0.18, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 6.0
      - positions: [0.15, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 9.0
      meta:
        name: Home
        usage: demo
        description: 'Go home'

    unfold_arm:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.30, 0.21, 0.35, -0.2, 0.8, -1.57, 1.37, 0.0]
        time_from_start: 4.0
      - positions: [0.30, 0.21, -0.2, -2.2, 1.15, -1.57, 0.2, 0.0]
        time_from_start: 6.0
      meta:
        name: unfold_arm
        usage: demo
        description: 'unfold_arm'

    reach_floor:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.19, 1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        time_from_start: 1.0
      - positions: [0.19, 1.6, -0.55, -1.35, 1.40, -1.57, -0.07, 0.0]
        time_from_start: 3.0
      - positions: [0.16, 1.6, -0.55, 0, 1.03, -1.57, -0.07, 0.0]
        time_from_start: 7.0
      meta:
        name: Reach Floor
        usage: demo
        description: 'Reach floor'

    reach_max:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.10, 1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        time_from_start: 1.0
      - positions: [0.33, 0.9, 0.68, -3.16, 1.10, 2.05, 1.0, 0.0]
        time_from_start: 4.0
      - positions: [0.33, 0.9, 1.05, -3.45, 0.45, 2.05, 1.0, 0.0]
        time_from_start: 7.0
      meta:
        name: Reach Max
        usage: demo
        description: 'Reach max'


    close_gripper:
      joints: [gripper_left_finger_joint, gripper_right_finger_joint]
      points:
      - positions: [0.0, 0.0]
        time_from_start: 0.5
      meta:
        name: close_gripper
        usage: demo
        description: 'close_gripper'

    close_gripper_half:
      joints: [gripper_left_finger_joint, gripper_right_finger_joint]
      points:
      - positions: [0.024, 0.024]
        time_from_start: 0.5
      meta:
        name: close_gripper_half
        usage: demo
        description: 'close_gripper_half'

    open_gripper:
      joints: [gripper_left_finger_joint, gripper_right_finger_joint]
      points:
      - positions: [0.044, 0.044]
        time_from_start: 0.5
      meta:
        name: open_gripper
        usage: demo
        description: 'open_gripper'

    head_tour:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [0, 0]
        time_from_start: 0.1
      - positions: [0.7, 0]
        time_from_start: 3.0
      - positions: [0.7, 0.3]
        time_from_start: 6.0
      - positions: [0.7, -0.3]
        time_from_start: 9.0
      - positions: [0.7, 0.3]
        time_from_start: 12.0
      - positions: [-0.7, 0.3]
        time_from_start: 15.0
      - positions: [-0.7, -0.3]
        time_from_start: 18.0
      - positions: [0, 0]
        time_from_start: 21.0
      meta:
        name: head_tour
        usage: demo
        description: 'head_tour'

    wave:
      joints: [arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint,
      arm_5_joint, arm_6_joint, arm_7_joint]
      points:
      - positions: [0.06337464909724033, -0.679638896132783, -3.1087325315620733, 2.0882339360702575, -1.1201172410014792, -0.031008601325809293, -2.0744261217334135]
        time_from_start: 0.0
      - positions: [0.06335930908588873, -0.7354151774072313, -2.939624246421942, 1.8341256735249563, -1.1201355028397157, -0.031008601325809293, -2.0744261217334135]
        time_from_start: 1.0
      - positions: [0.06335930908588873, -0.7231278283145929, -2.9385504456273295, 2.2121050027803877, -1.1201355028397157, -0.031008601325809293, -2.0744261217334135]
        time_from_start: 2.0
      - positions: [0.06335930908588873, -0.7354151774072313, -2.939624246421942, 1.8341256735249563, -1.1201355028397157, -0.031008601325809293, -2.0744261217334135]
        time_from_start: 3.0
      meta:
        name: Wave
        usage: demo
        description: 'wave'
    
    pregrasp_weight:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.10, 1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        time_from_start: 1.0
      meta:
        name: pregrasp_weight
        usage: demo
        description: 'Pregrasp weight'

    do_weights:
      joints: [arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        time_from_start: 1.0
      - positions: [1.6, -1.57, -3.16, 1.62, -1.57, -0.2, 0.0]
        time_from_start: 2.0
      - positions: [1.6, -0.90, -3.16, 2.0, -1.57, 0.35, 0.0]
        time_from_start: 4.0
      - positions: [1.6, -1.57, -3.16, 1.62, -1.57, -0.2, 0.0]
        time_from_start: 6.0
      - positions: [1.6, -0.90, -3.16, 2.0, -1.57, 0.35, 0.0]
        time_from_start: 8.0
      - positions: [1.6, -1.57, -3.16, 1.62, -1.57, -0.2, 0.0]
        time_from_start: 10.0
      - positions: [1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        time_from_start: 12.0
      meta:
        name: do_weights
        usage: demo
        description: 'Do weights'

    offer_gripper:
      joints: ['torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint', 'gripper_right_finger_joint', 'gripper_left_finger_joint']
      points:
      - positions: [0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.62, -1.577, 0.044, 0.044]
        time_from_start: 0.0
      meta:
        name: offer_gripper
        usage: demo
        description: 'offer_gripper'

    shake_hands:
      joints: ['gripper_left_finger_joint', 'gripper_right_finger_joint', 'torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint']
      points:
      - positions: [0.044, 0.044, 0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.53, -1.577]
        time_from_start: 0.0
      - positions: [0.035, 0.035, 0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.53, -1.577]
        time_from_start: 5.0
      - positions: [0.035, 0.035, 0.296, 1.61, -0.93, -3.14, 1.40, -1.577, -0.2, -1.577]
        time_from_start: 6.0
      - positions: [0.035, 0.035, 0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.53, -1.577]
        time_from_start: 7.0
      - positions: [0.035, 0.035, 0.296, 1.61, -0.93, -3.14, 1.40, -1.577, -0.2, -1.577]
        time_from_start: 8.0
      - positions: [0.035, 0.035, 0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.53, -1.577]
        time_from_start: 9.0
      - positions: [0.044, 0.044, 0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.53, -1.577]
        time_from_start: 11.0
      meta:
        name: shake_hands
        usage: demo
        description: 'shake_hands'

    pick_from_floor:
      joints: ['torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint', 'gripper_left_finger_joint', 'gripper_right_finger_joint']
      points:
      - positions: [0.226, 0.308, -0.695, -0.968, 1.582,  1.965, 0.273, -1.101, 0.044, 0.044]
        time_from_start: 0.0
      - positions: [0.12, 0.809, -1.197, -1.119, 0.322, 1.96, -0.849, 0.041, 0.044, 0.044]
        time_from_start: 4.0
      - positions: [0.12, 0.809, -1.197, -1.119, 0.345, 1.96, -0.849, 0.041, 0.0, 0.0]
        time_from_start: 6.0
      - positions: [0.27, 0.21, -1.153, -1.538, 2.306, 1.965, 0.394, -0.082, 0.0, 0.0]
        time_from_start: 9.0
      meta:
        name: pick_from_floor
        usage: demo
        description: 'Pick a shirt-like object from floor in front of the robot'

    show_manip_ws:
      joints: ['torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint']
      points:
      - positions: [0.237, 1.528, -0.089, -2.974, 0.186, 0.0, 0.0, -0.0]
        time_from_start: 0.0
      - positions: [0.238, 1.027, -0.033, -1.685, 1.243, 0.0, -0.0, -0.0]
        time_from_start: 2.0
      - positions: [0.238, 1.647, 0.02, 0.073, 1.569, 0.0, 0.0, -0.0]
        time_from_start: 4.0
      - positions: [0.10, 1.652, -0.373, 0.073, 1.162, 0.0, 0.0, -0.0]
        time_from_start: 6.0
      - positions: [0.10, 1.083, 0.578, 0.073, 2.087, 0.0, 0.0, -0.0]
        time_from_start: 8.0
      - positions: [0.10, 0.16, 0.271, 0.085, 1.771, 0.0, 0.0, -0.0]
        time_from_start: 10.0
      - positions: [0.10, 0.173, -0.477, 0.078, 1.076, 0.0, 0.0, -0.0]
        time_from_start: 12.0
      - positions: [0.10, 2.611, 0.217, 0.107, 1.771, 0.0, 0.0, -0.0]
        time_from_start: 14.0
      - positions: [0.10, 2.675, -0.443, 0.04, 1.136, 0.0, 0.0, -0.0]
        time_from_start: 15.0
      - positions: [0.10, 2.675, -0.443, 0.04, 1.136, 0.0, 0.0, -0.0]
        time_from_start: 16.0
      - positions: [0.235, 1.504, 0.082, -3.131, 0.883, 0.0, 0.0, -0.0]
        time_from_start: 18.0
      - positions: [0.33, 0.765, 0.662, -3.131, 0.508, -0.954, -1.117, -0.0]
        time_from_start: 20.0
      - positions: [0.33, 0.765, 0.662, -3.131, 0.508, -0.954, -1.117, -0.0]
        time_from_start: 21.0
      - positions: [0.33, 1.064, -0.083, -2.761, 1.168, -0.954, -1.117, -0.0]
        time_from_start: 23.0
      - positions: [0.33, 1.299, 0.079, -2.405, 0.501, -1.12, -0.651, 0.29]
        time_from_start: 24.0
      - positions: [0.33, 1.3, 0.079, -2.41, 0.5, 1.95, 0.0, 1.908]
        time_from_start: 26.0
      - positions: [0.33, 2.433, -0.02, -0.241, 2.082, 1.991, 0.0, 1.91]
        time_from_start: 28.0
      - positions: [0.33, 2.35, -0.82, -0.60, 1.80, 1.88, 1.10, 1.91]
        time_from_start: 29.0
      - positions: [0.33, 2.5, -0.823, -0.50, 1.71, 1.88, 1.10, 1.91]
        time_from_start: 30.0
      - positions: [0.33, 1.462, -1.323, -3.067, 2.193, 0.0, 0.0, -0.0]
        time_from_start: 32.0
      meta:
        name: show_manip_ws
        usage: demo
        description: 'show manipulation workspace'


