# Input topics handled/muxed by the twist mux.
# For each topic:
# - name    : name identifier to select the topic
# - topic   : input topic of geometry_msgs::Twist type
# - timeout : timeout in seconds to start discarding old messages, and use 0.0 speed instead
# - priority: priority in the range [0, 255]; the higher the more priority over other topics

topics:
-
  name    : navigation
  topic   : nav_vel
  timeout : 0.5
  priority: 10
-
  name    : joystick
  topic   : joy_vel
  timeout : 0.5
  priority: 100
-
  name    : keyboard
  topic   : key_vel
  timeout : 0.5
  priority: 90
-
  name    : tablet
  topic   : tab_vel
  timeout : 0.5
  priority: 100
-
  name    : marker
  topic   : marker_vel
  timeout : 0.5
  priority: 99
-
  name    : phone
  topic   : phone_vel
  timeout : 0.5
  priority: 98
-
  name    : rviz_joy
  topic   : rviz_joy_vel
  timeout : 0.5
  priority: 95
-
  name    : servoing_cmd_vel
  topic   : servoing_cmd_vel
  timeout : 0.5
  priority: 20
