torque_constant:
   arm_1_joint: 0.0735
   arm_2_joint: 0.0735
   arm_3_joint: -0.1149
   arm_4_joint: 0.1436
   arm_5_joint: 0.0 # 0.0487
   arm_6_joint: 0.0 # 0.0487
   arm_7_joint: 0.0 # 0.0487


torque_control:
  type: "walking_force_control/ArmTorqueControlComand"
  joints:
    - arm_1_joint
    - arm_2_joint
    - arm_3_joint
    - arm_4_joint

  base_link_name: "base_link"
  reference_signal: "circle"
  tip_link_name: "arm_7_link"
  hardware: True
  dt: 0.005


gravity_compensation:
  type: "walking_force_control/GravityCompensation"
  joints:
    - arm_1_joint
    - arm_2_joint
    - arm_3_joint
    - arm_4_joint
#    - arm_left_5_joint
#    - arm_left_6_joint
#    - arm_left_7_joint
  reference_signal: "circle"
  base_link_name: "base_link"
  tip_link_name: "arm_7_link"
  hardware: True

  friction:
   arm_1_joint: {s: 3.1, v: 0.4}
   arm_2_joint: {s: 3.1, v: 0.4}
   arm_3_joint: {s: 3.1, v: 0.4}
   arm_4_joint: {s: 1.3, v: 0.4}
   arm_5_joint: &default_friction {s: 0, v: 0}
   arm_6_joint: *default_friction
   arm_7_joint: *default_friction
   head_1_joint: *default_friction
   head_2_joint: *default_friction
   torso_lift_joint: *default_friction
   caster_back_left_1_joint: *default_friction
   caster_back_left_2_joint: *default_friction
   caster_back_right_1_joint: *default_friction
   caster_back_right_2_joint: *default_friction
   caster_front_right_1_joint: *default_friction
   caster_front_right_2_joint: *default_friction
   caster_front_left_1_joint: *default_friction
   caster_front_left_2_joint: *default_friction
   wheel_left_joint: *default_friction
   wheel_right_joint: *default_friction

