head_controller:
  ros__parameters:
    joints:
      - head_1_joint
      - head_2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 5.0
      head_1_joint:
        goal: 0.5
      head_2_joint:
        goal: 0.5
