joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    # TODO use_sim_time as argument
    use_sim_time: True  # comment when working with the robot
    publish_rate: 50.0
    extra_joints: 
      - 'caster_back_left_1_joint'
      - 'caster_back_left_2_joint'
      - 'caster_front_left_1_joint'
      - 'caster_front_left_2_joint'
      - 'caster_back_right_1_joint'
      - 'caster_back_right_2_joint'
      - 'caster_front_right_1_joint'
      - 'caster_front_right_2_joint'
      - 'suspension_left_joint'
      - 'suspension_right_joint'


